FROM rust:1.83-slim

WORKDIR /app

COPY Cargo.toml Cargo.lock ./
COPY src ./src
COPY ixml_tests /ixml_tests

# Build the debug binary
RUN cargo build --release --bin debug_tab

ENV RUST_BACKTRACE=0

CMD ["cargo", "run", "--release", "--bin", "debug_tab"]
